name: lza
on:
    schedule:
        # 0 minutes, 1 hour, every 3 days
        - cron: "0 1 */3 * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - run: yarn setup:az
            - run: yarn setup:bicep
            - name: lint bicep
              run: az bicep lint --file applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/02-spoke/deploy.spoke.bicep
            - name: compile
              run: yarn compile
            - name: lza_review 02-spoke
              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/02-spoke/deploy.spoke.bicep -ot $GITHUB_STEP_SUMMARY -l "review of 02-spoke -oa spoke.sarif"
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: Upload SARIF file
              if: success() || failure() # run this step even if previous step failed
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: spoke.sarif
            - name: lza_review all
              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/**/deploy.*.bicep -ot $GITHUB_STEP_SUMMARY -l "review of scenarios"
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: lza_review test
              run: yarn test:lza
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: Upload SARIF file
              if: success() || failure() # run this step even if previous step failed
              uses: github/codeql-action/upload-sarif@v3
              with:
                # Path to SARIF file relative to the root of the repository
                sarif_file: results.sarif
